### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by Tulasinathreddy** [Rajkumrdusad/Tool-X#11]
It is showing as
[+]Tool X not installed
[+]There are some errors
[+]please try again later.
Please help me....
I am using gnuroot Debian.

**Comment by Rajkumrdusad** [comment]
Ok let me check it what is error..

**Comment by Rajkumrdusad** [comment]
Sorry there are no any error found i am install it in my GNURoot Debian it is install properly.

**Comment by Tulasinathreddy** [comment]
Wait I will sent a screenalshot

**Comment by Rajkumrdusad** [comment]
So please check your internet connection and install properly i hope it will install if not install them inform me i will check it..

**Comment by Rajkumrdusad** [comment]
Please send screenshot..

**Comment by Tulasinathreddy** [comment]
Here

**Comment by Rajkumrdusad** [comment]
sorry i did not recive any screenshot.

**Comment by Rajkumrdusad** [comment]
I am tested Tool-X on GNURoot Debian and Termux and its working.

**Comment by hdhack** [comment]
How download this files in my phone???
