### ISSUE TITLE
dont know how to start the scripts of Tool-X . 

### ISSUE THREAD

**Issue by megaflappo** [Rajkumrdusad/Tool-X#13]
i installed Tool-X successfully on android. after installing i dont know how to start the programs i want to maybe e.g. reaver. wifite or something else. so can anyone explain me how i can start the tools. 

thank you very much. 

tapken_florian@yahoo.de

**Comment by Rajkumrdusad** [comment]
Hi @megaflappo don't worry i will explain.
First open your terminal (Termux) and type Tool-X to start Tool-X now type 1 to show all tools.
Type the number of tool that you want to install if tool-x say tool installed successfuly then exit from tool-x and type following commands to start the script that you have installed.

$ ls
it will display all installed tools.
$ cd yourtoolname
for example wifite
$ python2 wifite.py

any more query.
