### ISSUE TITLE
wpscan

### ISSUE THREAD

**Issue by peyu123** [Rajkumrdusad/Tool-X#15]
root@test:~/wpscan/bin# ruby wpscan
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- wpscan (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from wpscan:3:in `<main>'

root@test:~/wpscan/bin# cat /etc/issue
Ubuntu 16.04.5 LTS \n \l

root@test:~/wpscan/bin# uname -a
Linux test 2.6.32-042stab133.2 #1 SMP Mon Aug 27 21:07:08 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux

root@test:~/wpscan/bin# ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by Rajkumrdusad** [comment]
Hey @peyu123 wpscan is not my tool so i can't fix that issue. go wpscan repository and create that issue.
Sorry bro i can't help you in this metter. If there any issue in tool-x then tell me i will fix it.
