### ISSUE TITLE
Add This Great Termux Tool please

### ISSUE THREAD

**Issue by Sidi-Yahia** [Rajkumrdusad/Tool-X#17]
If you wish I propose to you to add EasY_HaCk Tool in your great script Tool-x and Thanks for you 
https://github.com/sabri-zaki/EasY_HaCk

**Comment by Rajkumrdusad** [comment]
thanks for information it will adding soon..

**Comment by Rajkumrdusad** [comment]
EasY_HaCk is added in Tool-X..
