### ISSUE TITLE
Command not found 

### ISSUE THREAD

**Issue by finessin87** [Rajkumrdusad/Tool-X#2]
I’ve installed the Tool-x successfully but every time I try to run it by typing Tool-X, it says command not found. What could be the problem?

**Comment by Rajkumrdusad** [comment]
Friend can you tell me one thing where are you installing tool x in Ubuntu or Termux or GnuRoot Debian terminal. Once i know that where are you installing so i can solve the error.

**Comment by Rajkumrdusad** [comment]
I am installing in Termux and GnuRoot Debian terminal it installed successfully and its running properly.

**Comment by Rajkumrdusad** [comment]
I am testing Tool-X at every platform it is working fine.

**Comment by Rajkumrdusad** [comment]
Ok friend thanks for the first issue. Now i find out what is the error in the tool-x. i solved that error.
