### ISSUE TITLE
Install errors on termux 

### ISSUE THREAD

**Issue by 5kedone** [Rajkumrdusad/Tool-X#21]
I keep getting Alot of sign into GitHub errors in  termux when running the install all command

**Comment by pranav22pv** [comment]
Yah I'm even getting it

**Comment by Rajkumrdusad** [comment]
i will try to fix it thanks for inform us..

**Comment by Rajkumrdusad** [comment]
Yes there are error but this error is not in termux the error in the link of some tools we have to update the link.
When this error come on the screen press CTRL+c it will install other all tools..

**Comment by 5kedone** [comment]
Also it seems to be having issues install some of the dependences for routersploit too

**Comment by Rajkumrdusad** [comment]
Yaa there are no any error in installation of tool. error come while installing the requriments of routersploit it will fix soon..

**Comment by dgazadkhan** [comment]
Hello Sir
When iam trying to run msfconsole command so it is not running and also cant install it in my mobile.

**Comment by Rajkumrdusad** [comment]
Hey dgazadkhan i am not sir we just bro or friends.
Show me the errors we will help you to install it..

**Comment by Rajkumrdusad** [comment]
we got error while installing metasploit it will fix soon...
Thans dgazadkhan..

**Comment by dgazadkhan** [comment]
Could not find nokogiri-1.8.0 in any of the sources
Run `bundle install` to install missing gems.
I tried many ways but it is not working.

**Comment by Rajkumrdusad** [comment]
ok wait...

**Comment by Rajkumrdusad** [comment]
Try this 
$ gem install nokogiri -- --use-system-libraries

**Comment by 5kedone** [comment]
Can't wait for fixed release will give it a test on fresh device when ready , please keep up the good work

**Comment by dogatthegate** [comment]
Good work bro.

**Comment by Rajkumrdusad** [comment]
Thanks bor..

**Comment by 5kedone** [comment]
Awesome work by the way , do you have a time line on the fixed version ?

**Comment by Rajkumrdusad** [comment]
No i have not timeline

**Comment by 5kedone** [comment]
No problems , will check back periodically lol

**Comment by n1ntendovee** [comment]
README.md       passwords.txt
hackinsta.py    screenshot.png
$ python hackinsta.py
This is a dead project, maybe one day i will rewrite it
Nice...

**Comment by Rajkumrdusad** [comment]
thanks for inform us it will removed soon..

**Comment by Rajkumrdusad** [comment]
But if you don't rewrite it so we will remove it..

**Comment by anx04** [comment]
Hi when I'm about to do the for command
Cd Tool-x. Nothing happen after that ,what am I doing wrong .thanks in advance bro

**Comment by Rajkumrdusad** [comment]
Yes because your command is wrong use following command :
$ cd Tool-X
it will work for you if any error please inform us we will help you

**Comment by bashkelvy** [comment]
Please I can't install any of "Tool-X" tools it keep giving connection problem despite with my fast internet speed.please,how can this be fixed?

**Comment by rajkumardusad** [comment]
> Please I can't install any of "Tool-X" tools it keep giving connection problem despite with my fast internet speed.please,how can this be fixed?

Hey @bashkelvy 
try following commands :
`$ apt install python`
`$ apt install python3`
`$ pip install requests`
`$ pip3 install requests`
I hope it will work for you?

**Comment by anx04** [comment]
thanks man .

**Comment by x13robotx** [comment]
I cant install Toolx  say error line and dont cant open it please can u help me master

**Comment by anx04** [comment]
Thx

**Comment by ffffaaasl** [comment]
P
