### ISSUE TITLE
Unable to install hydra from "tool category"

### ISSUE THREAD

**Issue by shiromoku** [Rajkumrdusad/Tool-X#24]
When i try to install it from tool category,it tells me that I need to connect to the Internet,but I can still install it through the tool list(show all tools)...

**Comment by Rajkumrdusad** [comment]
Yes May be there are some error we will fix it soon..

**Comment by Rajkumrdusad** [comment]
Thanks for inform us. It will fixed now you can install it. If you found any other error please inform us..
