### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Carter149** [Rajkumrdusad/Tool-X#25]
When I install Tool - X then I face problem Username, Password.
Password is not typing....

**Comment by Rajkumrdusad** [comment]
Yes because you are cloning wrong link
Try this :- 
git clone https://github.com/Rajkumrdusad/Tool-X.git

**Comment by Rajkumrdusad** [comment]
i hope error will be solved..

**Comment by syed-roshan01** [comment]
[ + ]  No network connection?
  [ + ]  Are you offline?
  [ + ]  Please try again after some time.
==>can anyone help me with this error

**Comment by rajkumardusad** [comment]
Hey @syed-roshan01 try following command : 
`$ pip install requests`
OR
`$ pip3 install requests`
i hope it works for you.

**Comment by syed-roshan01** [comment]
Thanks for your try @rajkumardusad 
but it's not working
it was working when it was of total tools 263 or something but when i updated it 
it showes me this when i try to downoad or clone a new one 
[ + ] No network connection?
[ + ] Are you offline?
[ + ] Please try again after some time.

**Comment by rajkumardusad** [comment]
New Tool-X v2.1 is running on python3 so install python3 and then try `pip install requests` may be it works.

**Comment by syed-roshan01** [comment]
bro i have installed even python3.7

**Comment by rajkumardusad** [comment]
Ok we will fix it as soon as possible.
You can use onex tool that is better the tool-x.
onex : https://github.com/rajkumardusad/onex

**Comment by syed-roshan01** [comment]
Ya bro thanks for your try and now i am using onex it's good
keep shining bro al the best 👍👍👍
but fix for this solution soon

**Comment by crabhi23** [comment]
No its not working plz help its not installing it shows no network connection?

**Comment by syed-roshan01** [comment]
> No its not working plz help its not installing it shows no network connection?

DM me on my insta @_syed_roshan_01

**Comment by rajkumardusad** [comment]
> No its not working plz help its not installing it shows no network connection?

Hey @Carter149 try following commands : 
`$ pip install requests`
`$ pip3 install requests`
Now open Tool-X it will works..

**Comment by crabhi23** [comment]
Its showing no network connection
Are u offline?
