### ISSUE TITLE
ADB-Toolkit adding request , please check it once

### ISSUE THREAD

**Issue by ASHWIN990** [Rajkumrdusad/Tool-X#26]
Sir please add this great ADB-Toolkit for linux in your script Tool-X , i would really appreciate your work .
https://github.com/ASHWIN990/ADB-Toolkit

Thanks SIR.

Hope you will add it soon

**Comment by Rajkumrdusad** [comment]
Yes it will be added soon and thanks for this great tool..

**Comment by Rajkumrdusad** [comment]
Your tool is added in Tool-X. Thanks for this great tool.
