### ISSUE TITLE
Error with tool install

### ISSUE THREAD

**Issue by vladoss1** [Rajkumrdusad/Tool-X#27]
After i type my login and pass i get :remote: Repository not found.                           fatal: repository 'https://github.com/shawarkhanethicalhacker/BruteXSS.git/' not found .Its a normal issue?

**Comment by Rajkumrdusad** [comment]
Ok we will check it..

**Comment by Rajkumrdusad** [comment]
Yes BruteXSS link was expired we updated the link it working now.
Thanks for inform us..

**Comment by vladoss1** [comment]
I got issues like this with some other tools ,i forgot to write it somewhere ,to tell.Sorry and thanks.

**Comment by Rajkumrdusad** [comment]
Yes there are lots of error please tell me the name of tools.

**Comment by vladoss1** [comment]
bruteXSS , Trity , D-TECT , spammer-grab , Hashzer , spammer-email , pyPIHSER , Parat , nWatch , TorStat , smap.

**Comment by Rajkumrdusad** [comment]
Thanks for help i will update the link of that tools as soon as posible.

**Comment by Rajkumrdusad** [comment]
all links are updated but two projects was deleted so we will replace them with another tool.

**Comment by vladoss1** [comment]
Thanks alot

**Comment by pronoob249** [comment]
No directory found named Tool X after installed it. Check it once fast

**Comment by Rajkumrdusad** [comment]
Yes everything is fine. there is no any error. it will automatically remove the directory after installation. type toolx or Tool-X to run this tool.

**Comment by pronoob249** [comment]
Thank you sir. Now its worked fine, good job.

**Comment by Rajkumrdusad** [comment]
Welcome sir..
i am not sir i am friend..

**Comment by Nuke-cpu** [comment]
ok so i installed the tool, after i install the tools i want, how do i open them? im having some trouble

**Comment by pronoob249** [comment]
Hello friend 
I'm back after 2yrs

**Comment by vladoss1** [comment]
Sup

вт, 5 янв. 2021 г., 23:48 pronoob249 <notifications@github.com>:
