### ISSUE TITLE
How to remove all the tools installed by Tool-X ?

### ISSUE THREAD

**Issue by Maestro0** [Rajkumrdusad/Tool-X#32]
Hi !
I tried to uninstall Tool-X and all the kali tools that already installed via: rm -T, OR Uninstall Tool-X, but the tool-x and all the other tools still there. 
How can I completely remove Tool-X and the other tools installed with it?

**Comment by Rajkumrdusad** [comment]
Hii @Maestro0 there are some error while uninstalling Tool-X using rm -T command.
Thanks for the issue we will fix it as soon as possible.

**Comment by Rajkumrdusad** [comment]
Hey @Maestro0 now you can uninstall Tool-X using rm -T command or uninstall tool-x command.

**Comment by Jirubizu** [comment]
@Rajkumrdusad How do you use the rm -T, it says T is not a valid option?

**Comment by Jirubizu** [comment]
for example how would I uninstall the tools installed too?
wouuld i just have to rm the individual folders inside my home folder?

**Comment by Rajkumrdusad** [comment]
Yes you have to remove individual tools
