### ISSUE TITLE
eeae

### ISSUE THREAD

**Issue by deadfishhackers** [Rajkumrdusad/Tool-X#33]
Add more scripts like hiddeneye

<hr>

<p align="center"><img src="http://oi63.tinypic.com/1t7ksj.jpg"></p>

**Comment by Rajkumrdusad** [comment]
Yaa why not we will add this tool and lost of more as soon as possible. Thanks for this tool suggestion..

**Comment by Rajkumrdusad** [comment]
Thia tool is added in Tool-X thanks for this amazing tool.

**Comment by wildborn** [comment]
I'm having a problem as some of my tools aren't getting installed like sudo etc and how to do attacks for WiFi networks without root

**Comment by deadfishhackers** [comment]
U can't deauth the net without root and even if u have root u might not be
able to do it cause some of kernels support WiFi injection and some dont
