### ISSUE TITLE
Unable to install tools and how to use tools without root

### ISSUE THREAD

**Issue by wildborn** [Rajkumrdusad/Tool-X#34]
I'm having a problem as some of my tools aren't getting installed like sudo etc and how to do attacks for WiFi networks without root

**Comment by Rajkumrdusad** [comment]
If you want to attack on wifi networks so please find out on google. there are some error while installing sudo we will fix it as soon as posible.

**Comment by Rajkumrdusad** [comment]
Thanks for inform us.

**Comment by wildborn** [comment]
Dear sir

 Thanking you for helping me out and clearing my queries and making me
understand about your useful tool .

The main problem leading me is I want to clear my basics by using some
tools on hacking and create something worthy so can you suggest or send me
some good stuff regarding WiFi hacking .

I look forward, you'll be helping me in the following conditions and in
clearing my doubts .

Regards
Lakshay Sharma

**Comment by Rajkumrdusad** [comment]
Hey @wildborn i am not sir i am your friend for wifi hacking if you are try to hack wifi with non rooted Android so don't worry you can't hack only you can perform bruteforce attack. It may be possible to hack wifi after rooting your Android.

**Comment by Rajkumrdusad** [comment]
This tool is provide a huge list of tools for hacking for Android that's it.
