### ISSUE TITLE
Some error in installation 

### ISSUE THREAD

**Issue by sdprogram** [Rajkumrdusad/Tool-X#35]
I can't install some tools like instahack,wifigod,smap,Devploit,
Hashzer,pyPISHER,

**Comment by sdprogram** [comment]
Please do something for this brother

**Comment by Rajkumrdusad** [comment]
Hey @sdprogram we will fix these error as soon as possible. Thanks for informing us it will be fixed soon.

**Comment by sdprogram** [comment]
thanks brother

**Comment by mo975** [comment]
please hurry up

**Comment by Rajkumrdusad** [comment]
Hey @mo975 what is the error please help us.

**Comment by Rajkumrdusad** [comment]
Hey @mo975  and @sdprogram there some error in links to these tools now they are ready for download if there are any error so please inform us.
