### ISSUE TITLE
How to run tools as root?

### ISSUE THREAD

**Issue by MademoiselleVictoire** [Rajkumrdusad/Tool-X#36]
Hey there!

Some tools are not launching and some are not effective enough without being rooted. Can you please share the tutorial how to root them? Also if you could post the how to use tutorial links for most effective tools.

Thank you so much!

**Comment by Rajkumrdusad** [comment]
Hey @MademoiselleVictoire if you are using in Android so its very difficult to use tools as a root if you want to run tools as a root you have to root your Android or try to install sudo in termux it very hard..
