### ISSUE TITLE
Aircrack-ng won't be installed 

### ISSUE THREAD

**Issue by Alias321** [Rajkumrdusad/Tool-X#38]
Hi i tried many times to install Aircrack-ng 
But it failed. Other scripts will be install correctly 
I attached error screenshot 
![Screenshot_20190725-095056](https://user-images.githubusercontent.com/39771536/61847960-baf43b00-aec1-11e9-83d8-6ed66b7c4b7d.png)

**Comment by Rajkumrdusad** [comment]
Hey @Alias321 there are some error while installing aircrack-ng we will try to solve it as soon as possible tnaks for inform us keep it up

**Comment by Rajkumrdusad** [comment]
Sorry @Alias321 we can not run aircrack-ng in termux it is for ubuntu now..

**Comment by Alias321** [comment]
@Rajkumrdusad that's so bad :(

**Comment by Rajkumrdusad** [comment]
Yaa i know but it not working in termux right now may be available soon.

**Comment by Alias321** [comment]
Ok thanks for your response 
How can i capture handshake with termux?

**Comment by Rajkumrdusad** [comment]
It is very difficult or not possible in termux.

**Comment by Alias321** [comment]
Is there a way to get handshake on Android?
