### ISSUE TITLE
Termux-OS  system

### ISSUE THREAD

**Issue by Potterli20** [Rajkumrdusad/Tool-X#39]
it is a very simple tool to install various OS.
https://github.com/Sanif007/tool-OS
https://github.com/EXALAB/AnLinux-Resources

**Comment by Rajkumrdusad** [comment]
that's great ?

**Comment by Potterli20** [comment]
emmm,It should be!

**Comment by Potterli20** [comment]
> 
> 
> that's great ?

emmm,It should be!

**Comment by Rajkumrdusad** [comment]
Yaa why not it is.

**Comment by Potterli20** [comment]
@Rajkumrdusad I would like to add some scripts, note that blackarch cannot be used on termux.

**Comment by Rajkumrdusad** [comment]
Yes bro.

**Comment by Potterli20** [comment]
Are you Chinese???

**Comment by Rajkumrdusad** [comment]
Noo I'm indian

**Comment by Potterli20** [comment]
okay

**Comment by Rajkumrdusad** [comment]
why you think that I'm chinese??

**Comment by Rajkumrdusad** [comment]
Whre are you from??

**Comment by Potterli20** [comment]
Because China's tone is Chinese.
I'm from China
