### ISSUE TITLE
Tool-X easily Installs on Fedora Linux

### ISSUE THREAD

**Issue by WildeGeist** [Rajkumrdusad/Tool-X#40]
Aloha, I simply copy/paste in su - # git clone https://github.com/Rajkumrdusad/Tool-X.git

cd Tool-X

chmod +x install.aex

sh install.aex

all at once, and poof! It is installed. It should work in all Linux this way. Thank you. Makes it easy to grab tools.

**Comment by Rajkumrdusad** [comment]
Hey @WildeGeist it is made for linux and specially for Android but it also work in almost all linux based system.
thanks for appreciate us we are happy to help you.
