### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by rajatgagat81** [Rajkumrdusad/Tool-X#41]
Issue in the time of cloning it asking for username or password

**Comment by Rajkumrdusad** [comment]
Hey @rajatgagat81 it will ask username and password because you are cloning wrong link.
so clone proper link it never ask these things..

**Comment by ch1ck3ns** [comment]
Sorry for asking and by the way I'm new... so what is it's proper link?

**Comment by Rajkumrdusad** [comment]
Hey @ch1ck3ns use following command 
$ git clone https://github.com/Rajkumrdusad/Tool-X.git
Its very common issue while cloning tools from github it will ask username and password it your are cloning invalid link.

**Comment by rajatgagat81** [comment]
Sir,the issue will remain same
Provide me some efficient solution.

**Comment by Rajkumrdusad** [comment]
Hey @rajatgagat81 there are no any issue please copy valid url and clone it it will work for you. open the tool-x page on github and copy the url it will work there are no any error regarding installation in tool-x.

**Comment by punit861** [comment]
when i run "cd tool-x" then ut shows no such file or directory.

**Comment by Rajkumrdusad** [comment]
Hi @punit861 why you are writing "cd tool-x" please write "cd Tool-X" it will works. What its very common error and if you see any error like no such file or directory you can check it by ls command !!
