### ISSUE TITLE
dont know

### ISSUE THREAD

**Issue by BOBTHEBUILDERR** [Rajkumrdusad/Tool-X#42]
port 9065 unable to connect

**Comment by Rajkumrdusad** [comment]
Sorry what the error i can't understand ?

**Comment by BOBTHEBUILDERR** [comment]
it automatically logs out

**Comment by Rajkumrdusad** [comment]
this error in tool-x or in any other tools that in tool-x ?

**Comment by BOBTHEBUILDERR** [comment]
in tool-X

**Comment by Rajkumrdusad** [comment]
We will check it soon and if any error we will fix it thanks for your help.

**Comment by BOBTHEBUILDERR** [comment]
@
![Screenshot from 2019-09-04 17-34-57](https://user-images.githubusercontent.com/38834484/64253572-16780680-cf0d-11e9-85ec-c0ba171fd296.png)

**Comment by BOBTHEBUILDERR** [comment]
bhai ye dubara tool x pr aajata hai continue krne ke baad (dont know if u understand hindi)

**Comment by Rajkumrdusad** [comment]
Haa bhai i can understand hindi..

**Comment by Rajkumrdusad** [comment]
Bhai screenshot send karo kya error hai uper jo screenshot hai usmen to koi error nahi hai aap toolx ya Tool-X type karoge to tool-x open ho jayega ye successfully install ho gaya hai..

**Comment by BOBTHEBUILDERR** [comment]
vohi kia tha type yehi problem hai bs tool-x directory khulti aur kuch b ni

**Comment by Rajkumrdusad** [comment]
Tool-X to install ho gaya hai start karne ke liye toolx ya Tool-X type karo terminal me.

**Comment by BOBTHEBUILDERR** [comment]
hogya theek reinstalled git
then it worked on Tool-X command
thank you

**Comment by BOBTHEBUILDERR** [comment]
![Screenshot from 2019-09-04 18-33-14](https://user-images.githubusercontent.com/38834484/64257185-6ad2b480-cf14-11e9-9061-29ec08829615.png)

**Comment by BOBTHEBUILDERR** [comment]
bhai apke isme top 3 tools konse hai ?

**Comment by Rajkumrdusad** [comment]
Top 3 matlab har ek tool ka alag alag kaam hota hai.

**Comment by BOBTHEBUILDERR** [comment]
apke favourate tools iske andr

**Comment by Rajkumrdusad** [comment]
Yaar pata nahi saare to best he hai metasploit,sqlmap etc.

**Comment by Blackboard-24** [comment]
Tool install ke bad open kaise kore?
Help please!

**Comment by Rajkumrdusad** [comment]
Hey @Blackboard-24 its very simple. Jab aap tool install karte ho tab tool-x aap ko ye bhee batata hai ki tool ko run kaise kare aap use dhyan se padhe aur steps ko folow karen ye bahut hee aasan hai.
