### ISSUE TITLE
Fb hacking target

### ISSUE THREAD

**Issue by masterpink0** [Rajkumrdusad/Tool-X#43]

**Comment by Rajkumrdusad** [comment]
hey @masterpink0 what's the issue?

**Comment by masterpink0** [comment]
Can you help me to get back my main account.my account is dissabled i dont know how to get back.pls help me.my masterpink0000@gmail.com:pink@0000

**Comment by Rajkumrdusad** [comment]
Hey @masterpink0 how can i help you?

**Comment by Srksayful2** [comment]
Need to learn termux hacking

**Comment by Rajkumrdusad** [comment]
Hey @Srksayful2 start learning its amazing
