### ISSUE TITLE
don't activate program

### ISSUE THREAD

**Issue by diadya** [Rajkumrdusad/Tool-X#44]
I have such a problem when the team writes, press any key to activate, I press, the program does not start
![Screenshot_2019-10-04-04-05-25-987_com termux](https://user-images.githubusercontent.com/53941328/66172256-3c074580-e65c-11e9-8e03-6b2d27dc3842.jpg)

**Comment by Rajkumrdusad** [comment]
To run Tool-X you have to type Tool-X or toolx command in your terminal.
