### ISSUE TITLE
Cant install 

### ISSUE THREAD

**Issue by 9ag0** [Rajkumrdusad/Tool-X#45]
Please help
![Screenshot_2019-10-04-16-28-51](https://user-images.githubusercontent.com/56160228/66207941-17938380-e6c5-11e9-8fd1-dfda23189a30.png)

**Comment by Rajkumrdusad** [comment]
Hey @9ag0 please try again my be it will install. If any error so inform us.

**Comment by 9ag0** [comment]
Sorry but steel can't install what can I do next ??

**Comment by Rajkumrdusad** [comment]
ok we will fix it as soon as possible. thanks for inform us

**Comment by 9ag0** [comment]
I think it's because my device is 32 bit.Please can you make Tool-X for 32 bit.

**Comment by Rajkumrdusad** [comment]
Ya may be we will check it

**Comment by 9ag0** [comment]
Ok thanks

**Comment by Rajkumrdusad** [comment]
Hey @9ag0 we will test this tool at 32-bit and 64-bit and if any error we found the we will fix it. thank for issue keep it up

**Comment by darknodi** [comment]
@Rajkumrdusad Thank for this Tool-X Interpreter. You are the Android Script Foundation. 

Can you add some OSINT's that contains scopes of pipl.com fullcontact, opencnam, hunter.io, securitytrails, dataprovider, etc, for phone numbers, email address, from Phone to emal, username, etc....

**Comment by Rajkumrdusad** [comment]
Hey @darknodi thank for appreciation. We will add some OSINT's tools in tool-x.
