### ISSUE TITLE
Run a tool

### ISSUE THREAD

**Issue by Sreejakb** [Rajkumrdusad/Tool-X#48]
I have install a tool but how to run that tool.

**Comment by Rajkumrdusad** [comment]
Hey @Sreejakb its very easy. when you install a tool tool-x display a massage how to run that tool so read that massage or google it how to run that tool. every tool have a different process to run.

**Comment by Sreejakb** [comment]
It says go to a folder
But how to go

**Comment by Rajkumrdusad** [comment]
Hey @Sreejakb you have to learn linux. Ist very simple to change directory in linux :
$ cd directoryname
