### ISSUE TITLE
How to remove this tools? 

### ISSUE THREAD

**Issue by developedkiddies** [Rajkumrdusad/Tool-X#5]

**Comment by Rajkumrdusad** [comment]
To remove the Tool-X open the terminal and type
$ Tool-X
It will open Tool-X now type
$ rm -T
OR type 
$ Uninstall Tool-X

It will uninstall Tool-X :+1:

**Comment by developedkiddies** [comment]
thanks you :) fast response.

**Comment by rajkamal7404** [comment]
Uninstall Tool-X or rm -t not work

**Comment by Rajkumrdusad** [comment]
first run Tool-X tool then `rm -t` or `uninstall Tool-X`.

**Comment by Taruntechme** [comment]
> To remove the Tool-X open the terminal and type
> $ Tool-X
> It will open Tool-X now type
> $ rm -T
> OR type
> $ Uninstall Tool-X
> 
> It will uninstall Tool-X

Not working bhi and tools are not installed too
