### ISSUE TITLE
Can't install anything

### ISSUE THREAD

**Issue by seyo-IV** [Rajkumrdusad/Tool-X#53]
_____           _    __  __
        |_   _|__   ___ | |   \ \/ /
          | |/ _ \ / _ \| |____\  /
          | | (_) | (_) | |____/  \
          |_|\___/ \___/|_|   /_/\_\ v2.0

 =============================================
|          Install Best Hacking Tool          |
 =============================================

  [ + ] Sorry ??
  [ + ] 'slowloris' is not Installed !!

_______________________________________________
===============================================
 ##>

I'm getting this error on every tool.

**Comment by seyo-IV** [comment]
hmm okay i have restarted Termux, now it works.

**Comment by Rajkumrdusad** [comment]
Ok @seyo-IV if there are any error so please inform us we will be happy to help you ..
