### ISSUE TITLE
Question: is there a list of tools which don't require root?

### ISSUE THREAD

**Issue by seyo-IV** [Rajkumrdusad/Tool-X#54]
Is there such a list or do I have to google for everything?

**Comment by Rajkumrdusad** [comment]
Hi @seyo-IV yes there are lots of tools that does not require any root and that tools run on termux also. but there are lost other tools require root and some tools not work on termux.

**Comment by Rajkumrdusad** [comment]
Sorry for that we can't make list of tools that don't require root. you can google it or you can check it.

**Comment by seyo-IV** [comment]
okay no list then :C

**Comment by Rajkumrdusad** [comment]
You can check out new tool onex. i think onex is better then tool-x and easy to use.

**Comment by JavaSergo** [comment]
you can send a link, please. I try to Google it also..

**Comment by Rajkumrdusad** [comment]
Yes here is the link https://github.com/Rajkumrdusad/onex
