### ISSUE TITLE
Tools installing problem. 

### ISSUE THREAD

**Issue by noman9192** [Rajkumrdusad/Tool-X#55]
Hello,
Everything is working fine but the tools included inside is not installing. Showing internet connection not found.
![Screenshot_2019-12-12-21-20-00-514_com termux](https://user-images.githubusercontent.com/41927695/70724872-9b9d6380-1d25-11ea-8097-48177ed641b8.jpg)

**Comment by Rajkumrdusad** [comment]
Hey @noman9192 may be your internet connection is slow. but if there are any error so we will fix it as soon as possible.
