### ISSUE TITLE
Problem running setoolkit

### ISSUE THREAD

**Issue by Ashutosh2512** [Rajkumrdusad/Tool-X#56]
Setoolkit was installed on my system, but whenever i try to run it using the command "setoolkit", it gives the error command not found. Any idea?Please help!!!!

**Comment by Rajkumrdusad** [comment]
Hey @Ashutosh2512 sorry you can't run setoolkit like this. so please follow proper instruction of setoolkit.

**Comment by 41KaALaN41** [comment]
my server and onex is not working

**Comment by Rajkumrdusad** [comment]
hey @41KaALaN41 what's the error.
