### ISSUE TITLE
Hashzer and Email-Spammer.

### ISSUE THREAD

**Issue by Unkown23** [Rajkumrdusad/Tool-X#57]
I want this tools, but I can't download it because have password.

**Comment by Rajkumrdusad** [comment]
Hey @Unkown23 I'm so sorry for that there is an invalid url of these tools we will fix it soon..

**Comment by Rajkumrdusad** [comment]
Now you can download email spammer. ther hashzer tools deleted by its author so we can't do anything for that.

**Comment by Unkown23** [comment]
ok
