### ISSUE TITLE
Get Not Found Error When Try To install All Tools on Termux

### ISSUE THREAD

**Issue by zgunz42** [Rajkumrdusad/Tool-X#6]
Hello @Rajikumrdusad, I am followed your instruction to install Tool-X on termux everything work well except when installing all tools, the shell show this warning: 
: not found: .all.aex:
and after that break all the installation processes, are some file just missing or what?

**Comment by jcdino** [comment]
Hello, after a update to the tool there give me the same error, the folder /home/.Tool-X does not exist.

**Comment by Rajkumrdusad** [comment]
don't worry i am updating Tool-X and solve these error :)

**Comment by Rajkumrdusad** [comment]
Now Tool-X is updated its working fine :-)
