### ISSUE TITLE
ErrorName 

### ISSUE THREAD

**Issue by excep** [Rajkumrdusad/Tool-X#7]
There is a problem. It said : 

Traceback (most recent call last):
  File ".Tool-X.aex", line 1, in <module>
    Blazy
NameError: name 'Blazy' is not defined

**Comment by Rajkumrdusad** [comment]
Ok i will check it..

**Comment by Rajkumrdusad** [comment]
please Can you tell me what is the error and when is show error.

**Comment by excep** [comment]
I installed it . But I want to run it I typed Tool-X to run it and it gives me this : 

NameError: name 'Blazy' is not defined

**Comment by Rajkumrdusad** [comment]
Ok got it now install it again i hope it will works..

**Comment by excep** [comment]
It still doesn't work. I installed it again but when I wanted to run it, I typed " Tool-X " and it gives me this :

Traceback (most recent call last):
  File ".Tool-X.aex", line 1, in <module>
    blazy.py
NameError: name 'blazy' is not defined

**Comment by Rajkumrdusad** [comment]
how you install it..

**Comment by Rajkumrdusad** [comment]
Type following commands

git clone https://github.com/Rajkumrdusad/Tool-X.git
cd Tool-X
sh install.aex

Now Type Tool-X i hope it will work..

**Comment by excep** [comment]
I had used this tool few days ago. and it worked very well.but now I used the same way I did before but it this issue is keep poping up

**Comment by Rajkumrdusad** [comment]
Ok Dear just try this command

rm -rf ~/.Tool-X
rm -rf /data/data/com.termux/files/usr/bin/Tool-X
git clone https://github.com/Rajkumrdusad/Tool-X.git
cd Tool-X
sh install.aex

Now Type Tool-X i hope it will work..

**Comment by Rajkumrdusad** [comment]
I am checking this tool in Termux and gnuroot debian terminal its work fine..

**Comment by Rajkumrdusad** [comment]
Ok let me explain

# according to your error

Traceback (most recent call last):
File ".Tool-X.aex", line 1, in 
blazy.py
NameError: name 'blazy' is not defined

there are error in .Tool-X.aex file in line no 1
Blazy is not define which mean blazy is not define in .Tool-X.aex file so that's why it is throwing an error.
I hope you got it need any more help just ask me i will help you..

**Comment by excep** [comment]
Thank you bro !! I realy appreciate it .
Do you use whatsapp ?

**Comment by Rajkumrdusad** [comment]
Yes

**Comment by excep** [comment]
Let me have your number ?

**Comment by Rajkumrdusad** [comment]
can i have your email because i not active on whatsapp so i think email is better.

**Comment by excep** [comment]
nouchidi@gmail.com

**Comment by Rajkumrdusad** [comment]
Ok i will send my email on this email..

**Comment by Rajkumrdusad** [comment]
ok can i know where are you from..

**Comment by Rajkumrdusad** [comment]
By the way i am from india.

**Comment by excep** [comment]
I'm from Morocco

**Comment by Rajkumrdusad** [comment]
Nice to meet you..

**Comment by excep** [comment]
Nice to meet you too bro  !!  So you are a hacker  ??

**Comment by Rajkumrdusad** [comment]
No i am not i am student..

**Comment by megaflappo** [comment]
hallo. i installed all tools successfullly on android. so now i really dont know how to start this scripts. could u explain me pls, how i start sripts after installing. if i type in the name of script i want to use nothing happens. thank u very much . this is my emailadress: tapken_florian@yahoo.de . maybe u can email me directly.

**Comment by wickj162** [comment]
Hi Raj,

In the installation it ask me the username and the password for www.github.com, it is normal ? Thanks in advance. (Sorry for my english)

**Comment by Seraphinfire** [comment]
Yes all is normal I got the same things for my upgrade 😊

**Comment by Rajkumrdusad** [comment]
Hi friends i am testing this tool in my terminal but it will never ask for username and password for github may be your are using somthing wrong command or link..

**Comment by bimalgupta1** [comment]
friend its ask for user name and pass  why...? can u tell me the reson behind

**Comment by Rajkumrdusad** [comment]
Hey @bimalgupta1 github ask username and password when you are cloning wrong link so please clone proper link it will never ask username and password..
