### ISSUE TITLE
Kali Linux Install

### ISSUE THREAD

**Issue by t1mb3rw0lf** [Rajkumrdusad/Tool-X#8]
Hello, I used Tool-X to install KaliLinux and don't know how to start it. I tried "ls", but there is no dir named "Tool-X" or "Kali" or smth. I tried to install Kali one more time, it took 100 mb of space but still there is no dir or command to start it. Please tell where is it located?

**Comment by Rajkumrdusad** [comment]
there are some error while installing kali linux in termux. It is solved.
i hope now it will work.
Please check it and tell me it works or not...

**Comment by Rajkumrdusad** [comment]
Please Update Tool-X and try to install kali linux and tell me it working or not i hope it works...
