### ISSUE TITLE
"Brutal" is malware.

### ISSUE THREAD

**Issue by Snow344** [Rajkumrdusad/Tool-X#9]
**Proof:**
<img src=https://i.imgur.com/oHihHdG.png>

**Comment by Snow344** [comment]
There's more.
<img src=https://i.imgur.com/flhz22B.png>

**Comment by Rajkumrdusad** [comment]
Brutal is malware. Now what can i do. brutal is not my tool but i can remove it from Tool-X.

**Comment by Rajkumrdusad** [comment]
i think Brutal is a toolkit to quickly create various payload,powershell attack , virus attack and launch listener for a Human Interface Device. I mean its use to create virus.

**Comment by Rajkumrdusad** [comment]
Sorry i can understand what you want to say. I think you asking for how to run Brutal. Tell me i am right or not..

**Comment by Snow344** [comment]
@Rajkumrdusad No, I'm asking how those trojans got there, because I didn't run Brutal at all.

**Comment by Rajkumrdusad** [comment]
Ok..

**Comment by Rajkumrdusad** [comment]
Brutal is malware but many people need brutal and they use it so i am not removing now it from Tool-X but if people don't  need Brutal so i will remove it..

**Comment by miiiiiYT** [comment]
# This may be a little late now, but due to the nature of "malware creation software" they often get marked as malware themselves, but there is absolutely no problem with these.

**Comment by guyfawkes69** [comment]
No please leave it there. It's fine where it is lol
